### ISSUE TITLE
Create backend working demo via OpenAI Assistant

### ISSUE THREAD

**Issue by TheAvailer** [jathonderulo/SwEngGroup27#20]
Necessary features:
- Retrieval (retrieving external data via file input)
- Generation (retrieved data can be passed to the LLM to be processed)

**Comment by wardr3** [comment]
## Updates:
- Assistant is now implemented and can answer questions passed through the frontend
- Responses are printed to the frontend
- The assistant can "remember" previous messages
## Outstanding issues:
- File handling is not implemented yet
- Our API key is causing the program to throw server errors, but the program works fine with a personal key
- There should be one thread per instance, connecting to a single backend Assistant, instead of using global objects
